### ISSUE TITLE
Lighthouse Quic Port

### ISSUE THREAD

**Issue by JoshMelton** [EOA-Blockchain-Labs/ethereumonarm#67]
https://lighthouse-blog.sigmaprime.io/Quic.html
and 
https://github.com/sigp/lighthouse/releases/tag/v4.5.0

Lighthouse clients as of v4.5.0, are able to to utilize a faster protocol than tcp, a protocol running on udp, called quic that benchmarks better in latency / bandwidth.

To enable this intra-lighthouse feature and gain the advantages you would need to allow port 9001/udp via the ufw rules you have in fpm-package-builder/utils/ethereumonarm-monitoring-extras/sources/usr/lib/ethereumonarm/user.rules

Cheers =)

**Comment by diglos** [comment]
Thanks for the info, will look into the firewall rules.

The firewall is disable by default, though.
