### ISSUE TITLE
Nethermind gnosis configuration

### ISSUE THREAD

**Issue by gwenvador** [EOA-Blockchain-Labs/ethereumonarm#71]
Nethermind does not start for gnosis chain as there is a mistake in the configuration file. --Metrics.Enabled true is added twice:
ARGS="--config gnosis  --loggerConfigSource /opt/nethermind/NLog.config -dd /home/ethereum/.nethermind --JsonRpc.JwtSecretFile /etc/ethereum/jwtsecret --Metrics.Enabled true --Metrics.Enabled true --Metrics.ExposePort 7070"

**Comment by diglos** [comment]
Updated.

Thanks for reporting.
