### ISSUE TITLE
Raspberry Pi 5 support?

### ISSUE THREAD

**Issue by cRoCx** [EOA-Blockchain-Labs/ethereumonarm#72]
Just wondering if support for Raspberry Pi 5 is feasible?
Specs-wise it's a step up from Pi 4 with its 2-3x CPU performance, 2x USB performance (for USB-SSD-Adapters) and M.2 HAT for SSDs via PCIe 2.0 x1. However, it is also RAM-limited to 8GB. Not sure, if that is the deal-breaker?

**Comment by diglos** [comment]
8 GB of RAM is really a great barrier. We will wait a little and see if there is a chance of getting a 16 GB version.

**Comment by wdpatti** [comment]
A 16GB edition of the Rpi5 is now out:
https://www.raspberrypi.com/products/raspberry-pi-5/

Another [project](https://www.web3pi.io/) has also proven that it is possible to run a node on a Pi in 2025.

**Comment by diglos** [comment]
Hi,

Yes, a 16 GB Rpi5 is capable of running a node. We already support it and an official image is available. Please see:

https://ethereum-on-arm-documentation.readthedocs.io/en/latest/quick-guide/download-and-install.html#raspberry-pi-5
